# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Juan Antonio Macías
tagline:          'Un loco más al que le gustan las matemáticas.'
description:      'Me he dejado las señales de suelo mojado en casa.'
url:              http://juanmtg.github.io
baseurl:          '/'
paginate:         5

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://juanmtg.github.io/images/avatar.png

author:
  nick:           'JuanMtg'
  name:           'Juan Antonio Macías'
  url:            https://twitter.com/juanmtg

# Custom vars
version:          1.0.0

github:           
  repo:           https://github.com/juanmtg

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: juanmtg
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: juanmtg
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  steam: juanmtg

# Your disqus shortname, entering this will enable commenting on posts
disqus: juanmtg